### ISSUE TITLE
keyhelper is giving me error

### ISSUE THREAD

**Issue by keyurgit45** [akashlilhare/news_app#1]
Target of URI doesn't exist: '../helper/key_helper.dart'.
Try creating the file referenced by the URI or using a URI for a file that exists.

this is the error. kindly help me with this.

**Comment by akashlilhare** [comment]
![image](https://user-images.githubusercontent.com/39927872/116010089-9864f800-a63a-11eb-8e4e-5242c8284cf7.png)

make `key_helpere.dart` in helper directory and use your own key from https://newsapi.org/

**Comment by keyurgit45** [comment]
thank you
